use Gabaritando

INSERT INTO Usuario (nome, userName, email, senha) VALUES
('Mayk Henrique'	, 'maykhsm'		, 'mayk.hsm@gmail.com'	, '123'),
('Rodney Oliveira'	, 'oliveirarodney', 'rodney.oliveira@aluno.ifsp.edu.br', 'abc'),
('Eduardo Machado'	, 'eduploch'	, 'eduploch@yahoo.com'	, '1234')

INSERT INTO Categoria (nomeCategoria) VALUES
('Ciência'),
('Cinema'),
('Esporte'),
('Geografia'),
('História'),
('Literatura'),
('Lógica'),
('Música'),
('Séries')


INSERT INTO Quiz VALUES	
('1'),
('2'),
('3')

INSERT INTO Pergunta (descricao, codCategoria) VALUES
--Ciência (completo)

('Quais os dois ramos da física que surgiram no começo do século XX e revolucionaram toda a concepção científica criada na área até então?',1),
('Qual o nome da matemática criada por Isaac Newton e Gottfried Wilhelm Leibniz?',1),
('Qual desses fenômenos explica a emissão irregular de ondas por corpos em movimento em relação ao observador?',1),
('A seguinte fórmula ''U = W+Q'' se refere à quê?',1),
('Qual das equações a seguir corresponde à 2ª Lei de Newton (Princípio fundamental da dinâmica)?',1),
('Em uma árvore, onde ocorre a fase fotoquímica da fotossíntese?',1),
('Qual o significado da sigla ATP?',1),
('Qual é a classificação do hélio?',1),
('Quais são as subdivisões de um átomo?',1),
('Quem descobriu a radioatividade?',1),
('Em 1897 foi criado o modelo atômico que ficou conhecido como ''pudim de passas''. Quem criou esse modelo?',1),
('Como foi descoberta a lei da gravidade, e por quem?',1),
('Que matemático e astrônomo é considerado o pai do heliocentrismo?',1),
('Que físico e astrônomo aperfeiçoou a luneta?',1),
('Qual é o nome cientifico da soja?',1),
('Qual é o nome científico do feijão-comum?',1),
('Qual é o nome cientifico da abóbora?',1),
('Qual é o nome científico da mandioca?',1),
('Qual é o nome científico do arroz?',1),
('Qual é o nome científico da alface?',1),
('Qual é o nome científico da uva?',1),
('Por que o vírus não é vivo?',1),
('Qual destes animais não pertence ao filo dos Artrópodes?',1),
('Qual é o nome Científico do Gorila?',1),
('Qual é o nome Científico do Calango?',1),
('Qual é o nome Científico da Pulga?',1),
('Qual é o nome científico da raposa?',1),
('Qual é a organela responsável pela síntese do DNA? Isso inclui os processos de transcrição, tradução e síntese.',1),
('No filo dos animais vertebrados, os denominados ''Ágnatos'' são aqueles que não possuem:',1),
('Quais são as unidades básicas para ser um ser vivo?',1)

INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
--Ciência (completo)
(  1, 0, 'Mecânica Quântica e Mecânica Relativística',1),
(  1, 1, 'Cosmologia e Astronomia',0),
(  1, 2, 'Física do Estado Sólido e Mecânica',0),
(  1, 3, 'Termodinâmica e Eletromagnetismo',0),
(  2, 0, 'Cálculo Diferencial e Integral',1),
(  2, 1, 'Binômio de Newton',0),
(  2, 2, 'Algoritmo de Gauss-Newton',0),
(  2, 3, 'Função',0),
(  3, 0, 'Efeito Doppler',1),
(  3, 1, 'Teoria da relatividade',0),
(  3, 2, 'Efeito Joule',0),
(  3, 3, 'Lei de Coloumb',0),
(  4, 0, 'Primeira lei da termodinâmica',1),
(  4, 1, 'Segunda lei de Newton',0),
(  4, 2, 'Equação de Torricelli',0),
(  4, 3, 'Primeira lei de Kepler',0),
(  5, 0, 'F = m.a',1),
(  5, 1, 'U = R.i',0),
(  5, 2, 'V²= Vo² + 2.a.Δs',0),
(  5, 3, 'V = Vo + a.t',0),
(  6, 0, 'Na folha, dentro do tilacoide',1),
(  6, 1, 'Na folha, dentro do cloroplasto',0),
(  6, 2, 'No tronco, dentro da xilema',0),
(  6, 3, 'No tronco, dentro dos vasos condutores',0),
(  7, 0, 'Trifosfato de adenosina',1),
(  7, 1, 'Tripolifosfato de sódio',0),
(  7, 2, 'Desoxiadenosina',0),
(  7, 3, 'Trifosfato de Guanosina',0),
(  8, 0, 'Gás nobre',1),
(  8, 1, 'Halogênio',0),
(  8, 2, 'Metal alcalino',0),
(  8, 3, 'Semi-metal',0),
(  9, 0, 'Prótons, elétrons, neutrons',1),
(  9, 1, 'Prótons, elétrons, cátions',0),
(  9, 2, 'Cátions, isótopos, neutrons',0),
(  9, 3, 'Elétrons, isóbaros, gama',0),
( 10, 0, 'Antoine Becquerel',1),
( 10, 1, 'Antoine Lavoisier',0),
( 10, 2, 'Albert Einstein',0),
( 10, 3, 'John Dalton',0),
( 11, 0, 'Thomson',1),
( 11, 1, 'Bohr',0),
( 11, 2, 'Rutherford',0),
( 11, 3, 'Proust',0),
( 12, 0, 'Com uma maçã por Isaac Newton',1),
( 12, 1, 'Com uma laranja por Isaac Newton',0),
( 12, 2, 'Com uma laranja por Galileu Galilei',0),
( 12, 3, 'Com uma maçã por Galileu Galilei',0),
( 13, 0, 'Nicolau Copérnico',1),
( 13, 1, 'Galileu Galilei',0),
( 13, 2, 'Johannes Kepler',0),
( 13, 3, 'Isaac Newton',0),
( 14, 0, 'Nicolau Copérnico',1),
( 14, 1, 'Edmond Halley',0),
( 14, 2, 'Christiaan Huygens',0),
( 14, 3, 'Galileu Galilei',0),
( 15, 0, 'Glycine max',1),
( 15, 1, 'Glycine spp.',0),
( 15, 2, 'Glycine merrill',0),
( 15, 3, 'Glycine hispida',0),
( 16, 0, 'Phaseolus vulgaris',1),
( 16, 1, 'Cucumis anguria',0),
( 16, 2, 'Cajanus cajan',0),
( 16, 3, 'Vigna unguiculata',0),
( 17, 0, 'Cucurbita pepo',1),
( 17, 1, 'Cucurbita esculenta',0),
( 17, 2, 'Solanum melongena',0),
( 17, 3, 'Solanum lycopersicum',0),
( 18, 0, 'Manihot esculenta',1),
( 18, 1, 'Merremia cissoides',0),
( 18, 2, 'Momordica charantia',0),
( 18, 3, 'Solanum tuberosum',0),
( 19, 0, 'Oryza sativa',1),
( 19, 1, 'Hordeum vulgare',0),
( 19, 2, 'Secale cereale',0),
( 19, 3, 'Humulus lupulus',0),
( 20, 0, 'Lactuca sativa',1),
( 20, 1, 'Cichorium intybus',0),
( 20, 2, 'Nasturtium officinale',0),
( 20, 3, 'Petroselinum crispum',0),
( 21, 0, 'Vitis vinifera',1),
( 21, 1, 'Vigna ungiculata',0),
( 21, 2, 'Vigna indica',0),
( 21, 3, 'Saintpaulia ionantha',0),
( 22, 0, 'Nenhuma das alternativas estão corretas',1),
( 22, 1, 'Pelo fato do vírus não possuir material genético',0),
( 22, 2, 'Pois é uma propriedade emergente',0),
( 22, 3, 'Por não possuir célula e não conseguir se reproduzir',0),
( 23, 0, 'Caracol',1),
( 23, 1, 'Aranha',0),
( 23, 2, 'Borboleta',0),
( 23, 3, 'Caranguejo',0),
( 24, 0, 'Gorilla gorilla',1),
( 24, 1, 'Furnarius rufus',0),
( 24, 2, 'Geochelone carbonaria',0),
( 24, 3, 'Chrysocyon brachyurus',0),
( 25, 0, 'Ameiva ameiva',1),
( 25, 1, 'Ovis aries',0),
( 25, 2, 'Paroaria coronata',0),
( 25, 3, 'Crotalus durissus',0),
( 26, 0, 'Vanellus chilensis',0),
( 26, 1, 'Mirmecofaga tridactila',0),
( 26, 2, 'Tolipeutes matacus',0),
( 26, 3, 'Felis concolor',0),
( 27, 0, 'Vulpes vulpes',1),
( 27, 1, 'Tripanossoma cruzi',0),
( 27, 2, 'Vanellus chilensis',0),
( 27, 3, 'Atta sexdens',0),
( 28, 0, 'RNA',1),
( 28, 1, 'ATP',0),
( 28, 2, 'DNA',0),
( 28, 3, 'Ácido desoxirribonucleico',0),
( 29, 0, 'Mandíbulas',1),
( 29, 1, 'Patas',0),
( 29, 2, 'Glândulas mamárias',0),
( 29, 3, 'Ossos',0),
( 30, 0, 'Célula',1),
( 30, 1, 'Reações químicas exotérmicas',0),
( 30, 2, 'Átomos',0),
( 30, 3, 'Radiações leves',0)
	  
--Cinema (completo)
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Quem dirigiu o filme ''Titanic'' com Leonardo DiCaprio lançado em 1997?',										2),
('Qual o nome do personagem principal do filme Clube da Luta?',													2),
('Qual o nome de batismo de Don Corleone em ''O Poderoso Chefão''?',											2),
('Qual o nome do diretor de ''O Poderoso Chefão''?',															2),
('Em que ano Spielberg ganhou o Oscar de ''Melhor Filme'' por A Lista de Schindler?',							2),
('Qual o nome do filme de terror dirigido por Stanley Kubrick que contou com a atuação de Jack Nicholson?',		2),
('Qual o primeiro trabalho de Judie Foster com Martin Scorsese?',												2),
('Qual o nome do personagem interpretado por Leonardo diCaprio em seu primeiro trabalho junto com Scorsese?',	2),
('Qual ator mais atuou em filmes do Scorsese?',																	2),
('Quantas vezes Clint Eastwood ganhou o Oscar de Melhor Diretor?',												2),
('Qual o nome do ator que interpreta Don Corleone em ''O Poderoso Chefão''?',									2),
('Qual o(a) ator(atriz) que mais venceu Oscars na história (até 2017)?',										2),
('Qual o filme mais vezes indicado ao Oscar na história (até 2017)?',											2),
('Qual foi a atriz mais jovem a ser premiada com o Oscar de Melhor Atriz?',										2),
('Qual desses filmes da saga ''Harry Potter'' não recebeu nenhuma indicação ao Oscar?',							2),
('Em qual desses filmes Leonardo Di Caprio não atuou?',															2),
('Quem é o diretor do filme Pulp Fiction?',																		2),
('Quem interpreta Peter Parker respectivamente em ''Homem Aranha'' e ''O Espetacular Homem Aranha''?',2),
('Quem é o diretor respectivamente em ''Homem Aranha'' e ''O Espetacular Homem Aranha''?',2),
('Em ''Harry Potter e a pedra filosofal'' quais as pessoas que levam Harry ainda bêbê a casa dos seus tios Dursley?',2),
('Qual o nome dos protagonistas de As Crônicas de Narnia, O Leão, A Feiticeira e o Guarda Roupa?',2),
('Quantos anos a atriz que representava a personagem Lúcia tinha quando atuou em As Crônicas de Narnia: Príncipe Caspian?',2),
('Em que ano foi lançado o filme As Crônicas de Narnia: A Viagem do Peregrino da Alvorada?',2),
('Quem é o criador de As Crônicas de Narnia?',2),
('No filme A Era do Gelo 4, Manny tem uma filha. Qual é o nome dela?',2),
('No filme ''O Rei Leão'', qual é o nome do filho do rei ?',2),
('Os criadores do filme ''Como Treinar o seu Dragão'' também deram origem a outros dois filmes. Quais são eles?',2),
('Quantos anos antes da aventura de ''O Senhor Dos Anéis'' a história O Hobbit acontece?',2),
('Qual é o nome do primeiro filme da trilogia ''O Hobbit''?',2),
('No seriado televisivo do Batman exibido entre 1966 e 1968, quem interpretou o Batman e o Coringa respectivamente?',2),
('Em ''Crepúsculo'', qual presente Bella ganha de Jake de aniversário?',2),
('No filme ''O Chamado'', depois de quantos dias a pessoa que assistiu a fita morre?',2),
('Qual o país em que se passa a história do filme ''Sweeney Todd: o barbeiro demoníaco da rua Fleet''?',2)

INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
--Cinema (completo)
( 31, 0,'James Cameron'			,1),
( 31, 1,'Steven Spielberg'		,0),
( 31, 2,'William Hale'			,0),
( 31, 3,'Clint Eastwood'			,0),
( 32, 0,'Tyler Durden'			,1),
( 32, 1,'Robert Paulson'			,0),
( 32, 2,'David Mills'			,0),
( 32, 3,'Jack Crowford'			,0),
( 33, 0,'Vito Andolini'			,1),
( 33, 1,'Vito Corleone'			,0),
( 33, 2,'Santiago Corleone'		,0),
( 33, 3,'Salvatore Mósi'			,0),
( 34, 0,'Francis Ford Coppola'	,1),
( 34, 1,'Martin Scorsese'		,0),
( 34, 2,'Quentin Tarantino'		,0),
( 34, 3,'Clint Eastwood'			,0),
( 35, 0,'1994'					,1),
( 35, 1,'1992'					,0),
( 35, 2,'1993'					,0),
( 35, 3,'1995'					,0),
( 36, 0,'O Iluminado'			,1),
( 36, 1,'Nascido Para Matar'		,0),
( 36, 2,'Glória Feitaa de Sangue',0),
( 36, 3,'A Morte Passou por Perto',0),
( 37, 0,'Alice Não Mora Mais Aqui',1),
( 37, 1,'Cassino'				,0),
( 37, 2,'Taxi Driver'			,0),
( 37, 3,'Os Infiltrados'			,0),
( 38, 0,'Amsterdam Vallon'		,1),
( 38, 1,'Travis Bickle'			,0),
( 38, 2,'Billy Costigan'			,0),
( 38, 3,'Jordan Belfort'			,0),
( 39, 0,'Robert De Niro'			,1),
( 39, 1,'Joe Pesci'				,0),
( 39, 2,'Leonardo Di Caprio'		,0),
( 39, 3,'Nicolas Cage'			,0),
( 40, 0,'2'						,1),
( 40, 1,'1'						,0),
( 40, 2,'3'						,0),
( 40, 3,'4'						,0),
( 41, 0,'Marlon Brando'			,1),
( 41, 1,'Al Pacino'				,0),
( 41, 2,'Robert Duvall'			,0),
( 41, 3,'John Cazale'			,0),
( 42, 0,'Katherine Hepburn'		,1),
( 42, 1,'Daniel Day-Lewis'		,0),
( 42, 2,'Meryl Streep'			,0),
( 42, 3,'Jack Nicholson'			,0),
( 43, 0,'Titanic (1998)'			,1),
( 43, 1,'Ben-Hur (1960)'			,0),
( 43, 2,'O Senhor dos Anéis - A Sociedade do Anel (2004)'		,0),
( 43, 3,'...E o Vento Levou (1939)'							,0),
( 44, 0,'Marlee Matlin (Os Filhos do Silêncio, 1986)'			,1),
( 44, 1,'Patty Duke (O Milagre de Anne Sullivan, 1962)'		,0),
( 44, 2,'Anna Paquin (O Piano, 1993)'							,0),
( 44, 3,'Brie Larson (O Quarto de Jack, 2015)'				,0),
( 45, 0,'Harry Potter e a Ordem da Fênix'						,1),
( 45, 1,'Harry Potter e a Pedra Filosofal'					,0),
( 45, 2,'Harry Potter e as Relíquias da Morte Parte I'		,0),
( 45, 3,'Harry Potter e o Prisioneiro de Azkaban'				,0),
( 46, 0,'Inimigos Públicos'									,1),
( 46, 1,'Os Infiltrados'										,0),
( 46, 2,'O Homem da Máscara de Ferro'							,0),
( 46, 3,'O Grande Gatsby'										,0),
( 47, 0,'Quentin Tarantino'									,1),
( 47, 1,'Martin Scorsese'										,0),
( 47, 2,'Christopher Nolan'									,0),
( 47, 3,'Zack Snyder' 										,0),
( 48, 0,'Tobey Maguire e Andrew Garfield',1),
( 48, 1,'Tobey Maguire e Aaron Johnson',0),
( 48, 2,'Tobey Maguire e Anton Yelchin',0),
( 48, 3,'Aaron Johnson e Andrew Garfield',0),
( 49, 0,'Sam Raimi e Marc Webb',1),
( 49, 1,'Stan Lee e Sam Raimi',0),
( 49, 2,'Stan Lee e Marc Webb',0),
( 49, 3,'Marc Webb e Sam Raimi',0),
( 50, 0,'Dumbledore, Minerva McGonagall e Hagrid',1),
( 50, 1,'Dumbledore, Hagrid e Snape',0),
( 50, 2,'Dumbledore, Hagrid e Quirrel',0),
( 50, 3,'Hagrid, Minerva McGonagall e Quirrel',0),
( 51, 0,'Lúcia, Susana, Pedro e Edmundo',1),
( 51, 1,'Amanda, Pedro, Suzana',0),
( 51, 2,'Edmundo, Carla, Lúcia, Pedro',0),
( 51, 3,'Aslan, Branca, Lúcia e Susana',0),
( 52, 0,'13',1),
( 52, 1,'09',0),
( 52, 2,'07',0),
( 52, 3,'16',0),
( 53, 0,'2010',1),
( 53, 1,'1999',0),
( 53, 2,'2012',0),
( 53, 3,'2006',0),
( 54, 0,'Clive Staples Lewis',1),
( 54, 1,'Joana D´arc',0),
( 54, 2,'Willian Moseley',0),
( 54, 3,'Stephenie Meyer',0),
( 55, 0,'Amora',1),
( 55, 1,'Morango',0),
( 55, 2,'Uvinha',0),
( 55, 3,'Cereja',0),
( 56, 0,'Simba',1),
( 56, 1,'Scar',0),
( 56, 2,'Covu',0),
( 56, 3,'Mufasa',0),
( 57, 0,'Kung Fu Panda e Shrek',1),
( 57, 1,'Monstros vs Alienígenas e Kung Fu Panda',0),
( 57, 2,'Madagascar e Shrek',0),
( 57, 3,'Carros e Bee Movie',0),
( 58, 0,'60',1),
( 58, 1,'50',0),
( 58, 2,'45',0),
( 58, 3,'25',0),
( 59, 0,'O Hobbit - Uma Jornada Inesperada',1),
( 59, 1,'O Hobbit - Uma Jornada Com anões',0),
( 59, 2,'O Hobbit - Como Tudo Começou',0),
( 59, 3,'O Hobbit - Lá e De Volta Outra Vez',0),
( 60, 0,'Adam West e Cesar Romero',1),
( 60, 1,'Adam West e Jack Nicholson',0),
( 60, 2,'Christian Bale e Heath Ledger',0),
( 60, 3,'Christian Bale e Jack Nicholson',0),
( 61, 0,'Um apanhador de sonhos',1),
( 61, 1,'Um amuleto',0),
( 61, 2,'Um anel',0),
( 61, 3,'Um pingente',0),
( 62, 0,'7 dias',1),
( 62, 1,'4 dias',0),
( 62, 2,'13 dias',0),
( 62, 3,'10 dias',0),
( 63, 0,'Inglaterra',1),
( 63, 1,'Canadá',0),
( 63, 2,'Estados Unidos',0),
( 63, 3,'Austrália',0)
      
--Esportes
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Quem foi o primeiro jogador negro a atuar oficialmente por um clube de futebol no Brasil?',							 3),
('Qual o país que mais sediou Jogos Olímpicos na história?',											     			 3),
('Qual piloto de Fórmula 1 faleceu após atropelar um fiscal nos anos 70?',												 3),
('Michael Schumacher foi o campeão em 7 temporadas na Formula 1. Em quais anos ele venceu?',							 3),
('Quando passou um período sem jogar basquete, qual outro esporte Michael Jordan jogou profissionalmente?',				 3),
('Quem foi o jogador mais jovem a atingir a marca de 20.000 pontos na NBA?',											 3),
('Quantas medalhas de ouro olímpicas já ganhou Usain Bolt?',															 3),
('Qual foi o país que teve a Olimpíada cancelada em 1916?',																 3), 
('Quem foi o artilheiro da edição do Campeonato Brasileiro de 2003?',													 3),
('Qual o atleta mais bem pago do mundo no ano de 2017 (Forbes)?',														 3),
('Qual foi o único time Sérvio a ganhar um título da UEFA Champions League?',											 3),
('Em que país nasceu o tenista Novak Djokovic?',																		 3),
('Qual o torneio mais velho e tradicional que existe no tênis?',														 3),
('Qual o primeiro boxeador a nocautear Myke Tyson, considerada até hoje uma das maiores zebras da história, em 1990?',	 3),
('Qual franquia foi a que mais venceu Super Bowls na história (até 2017)?',												 3),
('Qual a maior goleada da história da Copa do Mundo de Futebol?',														 3),
('Em qual país foi disputado a primeira Copa do Mundo de Futebol?',														 3),
('Qual seleção disputou mais finais de Copas do Mundo de Futebol na história?',											 3),
('Em que circuito ocorre as 24 horas de Le Mans?',																		 3),
('Qual piloto da Formula Indy foi tricampeão consecutivamente?',														 3)

--Esportes
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
( 64, 0, 'Miguel ''Migué'' do Carmo - Ponte Preta',1),
( 64, 1, 'Leônidas da Silva - São Paulo',0),
( 64, 2, 'Arthur Friedenreich - Germânia',0),
( 64, 3, 'Francisco Carregal - Bangu',0),
( 65, 0,'Estados Unidos',1),
( 65, 1, 'Reino Unido',0),
( 65, 2, 'França',0),
( 65, 3, 'Grécia',0),
( 66, 0, 'Tom Pryce',1),
( 66, 1, 'Brian McGuire',0),
( 66, 2, 'Mark Donohue',0),
( 66, 3, 'Helmuth Koinigg',0),
( 67, 0, '1994, 1995, 2000, 2001, 2002, 2003 e 2004',1),
( 67, 1, '1993, 1995, 1996, 2000, 2002, 2003 e 2004',0),
( 67, 2, '1993, 1995, 1996, 2000, 2002, 2003 e 2005',0),
( 67, 3, '1994, 1995, 1996, 2001, 2003, 2004 e 2005',0),
( 68, 0, 'Baseball',1),
( 68, 1, 'Futebol americano',0),
( 68, 2, 'Hockey',0),
( 68, 3, 'Futebol',0),
( 69, 0, 'LeBron James',1),
( 69, 1, 'Michael Jordan',0),
( 69, 2, 'Oscar Robertson',0),
( 69, 3, 'Kobe Bryant',0),
( 70, 0, '8',1),
( 70, 1, '9',0),
( 70, 2, '7',0),
( 70, 3, '10',0),
( 71, 0, 'Alemanha',1),
( 71, 1, 'França',0),
( 71, 2, 'Grécia',0),
( 71, 3, 'Estados Unidos',0),
( 72, 0, 'Dimba (Goiás)',1),
( 72, 1, 'Luís Fabiano (São Paulo)',0),
( 72, 2, 'Alex (Cruzeiro)',0),
( 72, 3, 'Washington (Atlético/PR)',0),
( 73, 0, 'Cristiano Ronaldo',1),
( 73, 1, 'LeBron James',0),
( 73, 2, 'Lionel Messi',0),
( 73, 3, 'Roger Federer',0),
( 74, 0, 'Estrela Vermelha',1),
( 74, 1, 'Partizan',0),
( 74, 2, 'Spartak Zlatibor Voda',0),
( 74, 3, 'Vojvodina',0),
( 75, 0, 'Sérvia',1),
( 75, 1, 'Rússia',0),
( 75, 2, 'República Tcheca',0),
( 75, 3, 'Ucrânia',0),
( 76, 0, 'Wimbledon',1),
( 76, 1, 'US Open',0),
( 76, 2, 'Roland Garros',0),
( 76, 3, 'Davis Cup',0),
( 77, 0, 'Buster Douglas',1),
( 77, 1, 'Evander Holyfield',0),
( 77, 2, 'Donovan Ruddock',0),
( 77, 3, 'Alex Stewart',0),
( 78, 0, 'Pittsburg Steelers',1),
( 78, 1, 'San Francisco 49ers',0),
( 78, 2, 'Dallas Cowboys',0),
( 78, 3, 'New England Patriots',0),
( 79, 0, 'Hungria 10 x 1 El Salvador',1),
( 79, 1, 'Alemanha 11 x 0 Arábia Saudita',0),
( 79, 2, 'Uruguai 8 x 0 Bolívia',0),
( 79, 3, 'Iugoslávia 11 x 1 Zaire',0),
( 80, 0, 'Uruguai',1),
( 80, 1, 'Inglaterra',0),
( 80, 2, 'Itália',0),
( 80, 3, 'França',0),
( 81, 0, 'Alemanha',1),
( 81, 1, 'Brasil',0),
( 81, 2, 'Itália',0),
( 81, 3, 'Argentina',0),
( 82, 0, 'Circuit de la Sarthe',1),
( 82, 1, 'Nurbürgring Nordscheifle',0),
( 82, 2, 'Fuji Speedway',0),
( 82, 3, 'Brands Hatch',0),
( 83, 0, 'Dario Franchitti',1),
( 83, 1, 'Scott Dixon',0),
( 83, 2, 'Sam Hornish Jr',0),
( 83, 3, 'Dan Wheldon',0)
    
--Geografia
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Quais países da américa tem o mesmo nome do que a capital?',									 4),
('Palikir é a capital de qual país?',															 4),
('Qual a capital do Fiji?',																         4),
('Qual a cidade mais populosa da África do Sul?',                                             	 4),
('Qual a cidade mais populosa da Nova Zelândia?',                                				 4),
('Quais as cores da bandeira de Pernambuco?',                                                    4),
('Quais países a Holanda colonizou?',                                                            4),
('O Brasil faz parte de qua(is) bloco(s) econômico(s)?',                                         4),
('Quais países fazem parte da América Anglo-Saxônica?',                                       	 4),
('Quais os quatro presidentes norte-americanos esculpidos no monte Rushmore?',				     4),
('O EUA faz parte de qua(is) bloco(s) econômico(s)?',                                            4),
('Qual dos seguintes países faz tanto parte do Mercosul, quanto da Comunidade Andina?',          4),
('Qual a maior montanha do continente americano?',                                             	 4),
('Quais os únicos países da Península Ibérica?',                                                 4),
('Entre os idiomas oficiais dos países americanos, qual destes não está incluso?',               4),
('Qual é a cidade mais populosa do continente americano?',                                       4),
('Qual dessas batalhas e guerras não ocorreram na Europa?',                                      4),
('Em 2016, qual país anunciou saída da União Européia?',                                         4),
('Qual o canal que liga dois mares e é importante rota comercial na África?',                    4),
('A Oceania tem qual apelido?',                                                                  4),
('Qual das auroras ocorrem na Antártida?',                                                       4),
('Qual a capital da Polônia?',                                                                   4),
('Qual a capital do Canadá?',                                                                    4),
('Qual a capital do Vietnã?',                                                                    4),
('Qual a capital da Tailândia?',                                                                 4),
('Quais desses países sulamericanos não possuem litoral?',                                       4),
('Quais desses países são banhados pelo oceano Pacífico?',                                       4),
('Qual o nome do oceano situado no extremo norte do planeta?',                                   4),
('O Havaí esta localizado em que oceano?',                                                 		 4),
('O Taj Mahal localiza-se em que cidade da Índia?',												 4)

--Geografia
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
( 84, 0, 'México e Guatemala',1),
( 84, 1, 'Guiana e Suriname',0),
( 84, 2, 'Cuba e Costa Rica',0),
( 84, 3, 'Nicarágua e Barbados',0),
( 85, 0, 'Micronésia',1),
( 85, 1, 'Moldávia',0),
( 85, 2, 'Filipinas',0),
( 85, 3, 'Nicarágua',0),
( 86, 0, 'Suva',1), 
( 86, 1, 'Nadi',0),
( 86, 2, 'Labasa',0),
( 86, 3, 'Lautoka',0),
( 87, 0, 'Joanesburgo',1),
( 87, 1, 'Cidade do Cabo',0),
( 87, 2, 'Pretória',0),
( 87, 3, 'Porto Elizabeth',0),
( 88, 0, 'Auckland',1),
( 88, 1, 'Wellington',0),
( 88, 2, 'Christchurch',0),
( 88, 3, 'Queenstown',0),
( 89, 0, 'Azul, amarelo, vermelho, verde e branco',1),
( 89, 1, 'Azul, vermelho, amarelo e branco',0),
( 89, 2, 'Preto, amarelo e vermelho',0),
( 89, 3, 'Verde, amarelho, azul, vermelho e preto',0),
( 90, 0, 'Aruba, Bonaire e Curaçao',1),
( 90, 1, 'Guadalupe, São Bartolomeu e Martinica',0),
( 90, 2, 'Montserrat, Bermudas e Anguilla',0),
( 90, 3, 'Santa Lúcia, Haiti e Dominica',0),
( 91, 0, 'Mercosul',1),
( 91, 1, 'Mercosul e NAFTA',0),
( 91, 2, 'Mercosul e APEC',0),
( 91, 3, 'Mercosul e ASEAN',0),
( 92, 0, 'EUA e Canadá',1),
( 92, 1, 'México, EUA e Canadá',0),
( 92, 2, 'México e EUA',0),
( 92, 3, 'Porto Rico, EUA e Canadá',0),
( 93, 0, 'George Washington, Thomas Jefferson, Theodore Roosevelt e Abraham Lincoln',1),
( 93, 1, 'George Washington, Thomas Jefferson, Benjamin Franklin e Abraham Lincoln',0),
( 93, 2, 'George Washington, Thomas Jefferson, Franklin D. Roosevelt e Abraham Lincoln',0),
( 93, 3, 'George Washington, John Adams, Benjamin Franklin e Abraham Lincoln',0),
( 94, 0, 'APEC e NAFTA',1),
( 94, 1, 'NAFTA e Mercosul',0),
( 94, 2, 'NAFTA',0),
( 94, 3, 'APEC e Mercosul',0),
( 95, 0, 'Bolívia',1),
( 95, 1, 'Chile',0),
( 95, 2, 'Argentina',0),
( 95, 3, 'Peru',0),
( 96, 0, 'Aconcágua',1),
( 96, 1, 'Everest',0),
( 96, 2, 'Chimborazo',0),
( 96, 3, 'K2',0),
( 97, 0, 'Espanha e Portugal',1),
( 97, 1, 'Itália e Grécia',0),
( 97, 2, 'França e Andorra',0),
( 97, 3, 'Noruega, Suécia e Finlândia',0),
( 98, 0, 'Alemão',1),
( 98, 1, 'Holandês',0),
( 98, 2, 'Francês',0),
( 98, 3, 'Inglês',0),
( 99, 0, 'Cidade do México',1),
( 99, 1, 'Nova York',0),
( 99, 2, 'São Paulo',0),
( 99, 3, 'Buenos Aires',0),
(100, 0, 'Guerra do Golfo',1),
(100, 1, 'Tomada da Bastilha',0),
(100, 2, 'Guerra dos Cem anos',0),
(100, 3, 'Revolução de 1848',0),
(101, 0, 'Reino Unido',1),
(101, 1, 'Alemanha',0),
(101, 2, 'Espanha',0),
(101, 3, 'França',0),
(102, 0, 'Canal do Suez',1),
(102, 1, 'Canal do Cabo',0),
(102, 2, 'Canal da Mancha',0),
(102, 3, 'Canal do Mediterrâneo',0),
(103, 0, 'Novíssimo mundo',1),
(103, 1, 'Novo mundo',0),
(103, 2, 'Velho mundo',0),
(103, 3, 'Velhíssimo mundo',0),
(104, 0, 'Austral',1),
(104, 1, 'Boreal',0),
(104, 2, 'Meridional',0),
(104, 3, 'Setentrional',0),
(105, 0, 'Varsóvia',1),
(105, 1, 'Cracóvia',0),
(105, 2, 'Poznan',0),
(105, 3, 'Breslávia',0),
(106, 0, 'Ottawa',1),
(106, 1, 'Toronto',0),
(106, 2, 'Vancouver',0),
(106, 3, 'Montreal',0),
(107, 0, 'Hanói',1),
(107, 1, 'Chiang Mai',0),
(107, 2, 'Jacarta',0),
(107, 3, 'Kuala Lumpur',0),
(108, 0, 'Bangcoc',1),
(108, 1, 'Chiang Mai',0),
(108, 2, 'Jacarta',0),
(108, 3, 'Kuala Lumpur',0),
(109, 0, 'Paraguai e Bolívia',1),
(109, 1, 'Uruguai e Paraguai',0),
(109, 2, 'Peru e Argentina',0),
(109, 3, 'Equador e Venezuela',0),
(110, 0, 'EUA, Rússia, México e Equador',1),
(110, 1, 'Brasil, Japão, Peru e México',0),
(110, 2, 'China, Venezuela, Chile e Colômbia',0),
(110, 3, 'Argentina, EUA, Canadá e Austrália',0),
(111, 0, 'Oceano Glacial Ártico',1),
(111, 1, 'Oceano Índico',0),
(111, 2, 'Oceano Pacífico',0),
(111, 3, 'Oceano Glacial Antártico',0),
(112, 0, 'Oceano Pacífico',1),
(112, 1, 'Oceano Atlântico',0),
(112, 2, 'Oceano Índico',0),
(112, 3, 'Oceano Glacial Ártico',0),
(113, 0, 'Agra',1),
(113, 1, 'Mumbai',0),
(113, 2, 'Nova Delhi',0),
(113, 3, 'Calcutá',0)

--Música 
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Qual música do Oasis é tema do filme ''Efeito Borboleta''?',																			7),
('Qual foi o primeiro single do álbum ''Back to Black'' da cantora Amy Winehouse?',														7),
('Qual a nacionalidade de M.Shadows, vocalista da banda Avenged Sevenfold?',															7),
('Em que ano foi lançado o álbum homônimo de estréia da banda Foo Fighters?',															7),
('Qual o nome do álbum do Nirvana considerado como um dos marcos do movimento grunge?',													7),
('Qual é a música usada como sample em Jorge da Capadócia dos Racionais MCs?',															7),
('Qual o nome do projeto paralelo conduzido por Dave Grohl que uniu grandes astros como Paul McCartney, Trent Reznor e Josh Homme?',	7),
('Qual é o(a) artista que cantava em uma banda nos anos 90 e agora trabalha exclusivamente com moda?',									7),
('Qual o primeiro single do cantor Justin Bieber?',																						7),
('David Gilmour é guitarrista de uma influente banda britânica. Qual banda é essa?',													7),
('Tony Iommi é integrante da formação original da banda Black Sabbath. Qual a função dele na banda?',									7),
('Qual das bandas abaixo não é britânica?',																								7),
('Quais eram os integrantes da banda Led Zeppelin?',																					7),
('O CD ''Millenium'', do Backstreet Boys, vendeu quantas cópias na primeira semana?',													7),
('Qual o nome completo do Michael Jackson?',																							7),
('Qual é o nome da canção que Michael Jackson gravou no Pelourinho, em Salvador?',														7),
('Qual o nome do primeiro álbum lançado pelo Queen?',																					7),
('Para quem Freddie Mercury compôs a música ''Love Of My Life''?',																		7),
('Qual desses álbuns do The Killers não é um álbum de estúdio?',																		7),
('Antes de ficar mundialmente conhecida como U2, a banda teve outros três nomes. Quais foram?',											7),
('Sobre o que se trata a música ''Janie''s Got a Gun'', do Aerosmith?',																	7),
('No álbum ''In The Zone'' de Britney Spears, lançado em 2003, tem a participação de Madonna em uma faixa. Qual é o nome da música?',	7),
('Em 2013, Katy Perry lança um novo single para o álbum Prism. Qual o nome do primeiro single lançado?',								7),
('Michael Jackson tem o álbum mais vendido da história da música pop. Qual é esse álbum?',												7),
('Em 2013 Lady Gaga lança o novo álbum Artpop. Qual foi o primeiro single à vir as rádios?',											7),
('Qual álbum da banda Red Hot Chili Peppers tem na capa uma piscina pegando fogo?',														7),
('Qual foi o primeiro álbum de estúdio de Rihanna?',																					7),
('No álbum ''Stripped'' de Christina Aguilera lançado em 2002, teve participação de Alicia Keys em qual faixa?',						7),
('Nicole Scherzinger fazia parte de qual grupo pop?',																					7),
('Qual é o clipe mais caro da história da música, onde o cantor (a) gastou 7 milhões de dólares?',										7)
  
--Música
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
(114, 0, 'Stop Crying Your Heart Out', 							1),
(114, 1, 'Don''t Look Back in Anger',							0),
(114, 2, 'Don''t Go Away',										0),
(114, 3, 'Champagne Supernova',									0),
(115, 0, 'Rehab',												1),
(115, 1, 'Back to Black',										0),
(115, 2, 'You Know I''m No Good',								0),
(115, 3, 'Tears Dry On Their Own',								0),
(116, 0, 'Estados Unidos',										1),
(116, 1, 'Austrália',											0),
(116, 2, 'Inglaterra',											0),
(116, 3, 'Irlanda',												0),
(117, 0, '1995',												1),
(117, 1, '1994',												0),
(117, 2, '1996',												0),
(117, 3, '1993',												0),
(118, 0, 'Nevermind',											1),
(118, 1, 'In Utero',											0),
(118, 2, 'Unplugged MTV',										0),
(118, 3, 'Bleach',												0),
(119, 0, 'Isaac Hayes - Ike’s Rap 2',							1),
(119, 1, 'Portished - Glory Box',								0),
(119, 2, 'Alessa Cara - Here',									0),
(119, 3, 'Jorge Ben Jor - Solta o Pavão',						0),
(120, 0, 'SoundCity',											1),
(120, 1, 'Audioslave',											0),
(120, 2, 'Probot',												0),
(120, 3, 'Them Crooked Vultures',								0),
(121, 0, 'Victoria Beckham',									1),
(121, 1, 'Donatella Versace',									0),
(121, 2, 'Justin Timberlake',									0),
(121, 3, 'Ashley Olsen',										0),
(122, 0, 'One Time',											1),
(122, 1, 'Baby (ft. Ludacris)',									0),
(122, 2, 'One Less Lonely Girl',								0),
(122, 3, 'Somebody to Love',									0),
(123, 0, 'Pink Floyd',											1),
(123, 1, 'Led Zeppelin',										0),
(123, 2, 'The Who',												0),
(123, 3, 'Black Sabbath',										0),
(124, 0, 'Guitarrista base',									1),
(124, 1, 'Baixista',											0),
(124, 2, 'Baterista',											0),
(124, 3, 'Vocalista',											0),
(125, 0, 'The Doors',											1),
(125, 1, 'Iron Maiden',											0),
(125, 2, 'Pink Floyd',											0),
(125, 3, 'Black Sabbath',										0),
(126, 0, 'Jimmy Page, John Bonham, John Paul Jones e Robert Plant',1),
(126, 1, 'Ian Gillan, John Bonham, David Gilmour e Robert Plant',	0),
(126, 2, 'Jimmy Page, Keith Moon, John Paul Jones e Robert Plant',	0),
(126, 3, 'Jimmy Page, Keith Moon, David Gilmour e Dio',			0),
(127, 0, 'Um milhão e cem mil cópias',								1),
(127, 1, 'Três milhões de cópias',									0),
(127, 2, 'Dois milhões e quinhentos mil cópias',					0),
(127, 3, 'Um milhão e oitocentos mil cópias',						0),
(128, 0, 'Michael Joseph Jackson',									1),
(128, 1, 'Michael James Jackson',									0),
(128, 2, 'Michael Louis Jackson',									0),
(128, 3, 'Michael Phillip Jackson',								0),
(129, 0, 'They Don''t Care About Us',								1),
(129, 1, 'Billie Jean',											0),
(129, 2, 'You are not Alone',										0),
(129, 3, 'Bad',													0),
(130, 0, 'Queen',													1),
(130, 1, 'Sheer Heart Attack',										0),
(130, 2, 'A Night at the Opera',									0),
(130, 3, 'A Day at the Races',										0),
(131, 0, 'Mary Austin',											1),
(131, 1, 'Kashmira Bulsara',										0),
(131, 2, 'Jim Hutton',												0),
(131, 3, 'Peter Freestone',										0),
(132, 0, 'Sawdust',												1),
(132, 1, 'Sam''s Town',											0),
(132, 2, 'Day & Age',												0),
(132, 3, 'Battle Born',											0),
(133, 0, '''The Larry Mullen Band'', ''The Hype'' e ''Feedback''',	1),
(133, 1, '''Boys of Dublin'', ''Irish Boys'' e ''Bono''',			0),
(133, 2, '''Boys'', ''The Electric Co.'' e ''The Bono''s Band''',	0),
(133, 3, '''The Edge'', ''The Unforgettable Fire'' e ''The Joshua Tree''',	0),
(134, 0, 'Uma garota que mata o padrasto que a violentava',				1),
(134, 1, 'Uma garota que tenta se suicidar com uma faca',					0),
(134, 2, 'É sobre a filha mais velha de Steven',							0),
(134, 3, 'Sobre uma manchete que eles viram nos jornais',					0),
(135, 0, 'Me Against The Music',											1),
(135, 1, 'Toxic',															0),
(135, 2, 'Circus',															0),
(135, 3, '...Baby One More Time',											0),
(136, 0, 'Roar',															1),
(136, 1, 'Hot N'' Cold',													0),
(136, 2, 'Walking On Air',													0),
(136, 3, 'Firework',														0),
(137, 0, 'Thriller',														1),
(137, 1, 'Ben',															0),
(137, 2, 'Dangerous',														0),
(137, 3, 'Bad',															0),
(138, 0, 'Applause',														1),
(138, 1, 'Swine',															0),
(138, 2, 'Artpop',															0),
(138, 3, 'Venus',															0),
(139, 0, 'Californication',												1),
(139, 1, 'By The Way',														0),
(139, 2, 'Blood Sugar Sex Magik',											0),
(139, 3, 'Out In L.A.',													0),
(140, 0, 'Music Of The Sun',												1),
(140, 1, 'Good Girl Gone Bad',												0),
(140, 2, 'Loud',															0),
(140, 3, 'Unapologetic',													0),
(141, 0, 'Impossible',														1),
(141, 1, 'Beautiful',														0),
(141, 2, 'Dirrty',															0),
(141, 3, 'Can''t Hold Us Down',											0),
(142, 0, 'The Pussycat Dolls',												1),
(142, 1, 'TLC',															0),
(142, 2, 'Spice Girls',													0),
(142, 3, 'Destiny''s Child',												0),
(143, 0, 'Michael Jackson - Scream (feat. Janet Jackson)',					1),
(143, 1, 'Madonna - Express Yourself',										0),
(143, 2, 'Madonna - Die Another Day',										0),
(143, 3, 'Guns N'' Roses - Estranged',										0)

--História
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('A Era Vargas é o período da história nacional em que o Brasil foi governado por Getúlio Vargas. Qual o período correspondente?',		5),
('Qual o nome do deus do vinho na mitologia grega?',																					5),
('Qual o nome dado pelos romanos à deusa grega Afrodite?',																				5),
('Quais dos deuses abaixo não fazem parte da mitologia grega?',																			5),
('Em que ano iniciou-se a Revolução Francesa?',																							5),
('Qual foi o evento que marcou o início da Revolução Francesa?',																		5),
('Qual das características abaixo era uma das principais dos maias?',																	5),
('Em que local do mundo os povos astecas, maias e incas se estabeleceram?',																5),
('Em que ano Adolf Hitler tentou realizar um golpe de Estado em Munique junto com outros líderes do Partido Nazista?',					5),
('A Guerra Fria aconteceu durante quais anos?',																							5),
('Quem era o presidente do Brasil durante a Segunda Guerra Mundial?',																	5),
('Como chamava a aliança militar formada pelos países soviéticos com a URSS durante a Guerra Fria?',									5),
('Qual marco ocorrido no ano de 1939, é dado como o ponto inicial da Segunda Grande Guerra?',											5),
('Na Primeira Guerra Mundial, quem foi o primeiro país a declarar guerra a Iugoslávia?',												5),
('Quem era o ditador soviético durante a Segunda Guerra Mundial?',																		5),
('Qual o principal fator para o desenvolvimento da sociedade egípcia?',																	5),
('Por quê os egípcios desenvolveram a prática de embalsamar o corpo humano?',															5),
('Croácia e Sérvia integravam qual país antes de se tornarem independentes?',															5),
('Quais países integravam o eixo na Segunda Guerra Mundial?',																			5),
('Qual porto americano foi atacado pelos japoneses fazendo com que os EUA entrassem na guerra?',										5),
('Em qual país os brasileiros mais atuaram na Segunda Guerra Mundial?',																	5),
('Onde fica a Normandia, local do desembarque aliado no Dia D?',																		5),
('O ser humano atual descende de qual espécie?',																						5),
('O que foi o Iluminismo?',																												5),
('Quais os principais filósofos do Iluminismo?',																						5),
('Qual o maior cientista grego? ',																										5),
('A Batalha das Termópilas onde 300 soldados defenderam Esparta ocorreu contra qual Império?',											5),
('Na Idade Antiga existia uma escrita feita pelos egípcios. Qual é o nome desta escrita?',												5),
('Em que ano a Constantinopla foi conquistada pelos turcos durante a Idade Média?',														5),
('Quem foi o rei babilônico que mandou construir os jardins Suspensos de Babilônia?',												 	5)

--História
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
(144, 0,'1930-1945',														1),
(144, 1,'1930-1964',														0),
(144, 2,'1920-1945',														0),
(144, 3,'1940-1964',														0),
(145, 0,'Dioniso',															1),
(145, 1,'Apolo',															0),
(145, 2,'Ares',															0),
(145, 3,'Hércules',														0),
(146, 0,'Vênus',															1),
(146, 1,'Pandora',															0),
(146, 2,'Era',																0),
(146, 3,'Íris',0),
(147, 0,'Thor e Hórus',1),
(147, 1,'Ares e Hermes',0),
(147, 2,'Baco e Hades',0),
(147, 3,'Atena e Apolo',0),
(148, 0,'1789',1),
(148, 1,'1769',0),
(148, 2,'1800',0),
(148, 3,'1795',0),
(149, 0,'A Queda da Bastilha',1),
(149, 1,'A Revolta dos Sans-Culottes',0),
(149, 2,'Napoleão Bonaparte assumir a França',0),
(149, 3,'A invenção da Guilhotina',0),
(150, 0,'Tinham o domínio da astronomia',1),
(150, 1,'Eram grandes guerreiros, com organização militar poderosa',0),
(150, 2,'Desenvolveram muitas técnicas agrícolas',0),
(150, 3,'Tinham cidades independentes e autônomas',0),
(151, 0,'América',1),
(151, 1,'África',0),
(151, 2,'Europa',0),
(151, 3,'Ásia',0),
(152, 0,'1923',1),
(152, 1,'1921',0),
(152, 2,'1925',0),
(152, 3,'1927',0),
(153, 0,'1947 - 1991',1),
(153, 1,'1949 - 1989',0),
(153, 2,'1949 - 1996',0),
(153, 3,'1945 - 1989',0),
(154, 0,'Getúlio Vargas',1),
(154, 1,'José Sarney',0),
(154, 2,'Juscelino Kubitschek',0),
(154, 3,'Eurico Gaspar Dutra',0),
(155, 0,'Pacto de Varsóvia',1),
(155, 1,'Aliados',0),
(155, 2,'Entente',0),
(155, 3,'Tratado de Windsor',0),
(156, 0,'A invasão da Alemanha Nazista à Polônia',1),
(156, 1,'A aliança feita por Adolf Hitler e Benito Mussolini',0),
(156, 2,'O bombardeio japonês aos navios americanos ancorados na base naval de Pearl Harbor',0),
(156, 3,'O ataque da Alemanha Nazista à França',0),
(157, 0,'Império Austro-Húngaro',1),
(157, 1,'Alemanha',0),
(157, 2,'Império Otomano',0),
(157, 3,'EUA',0),
(158, 0,'Stálin',1),
(158, 1,'Lenin',0),
(158, 2,'Khrushchov',0),
(158, 3,'Brejnev',0),
(159, 0,'O rio Nilo',1),
(159, 1,'As pirâmides de Gizé',0),
(159, 2,'O deserto',0),
(159, 3,'Seus escravos',0),
(160, 0,'Pois depois da morte, a alma podia voltar ao corpo mumificado',1),
(160, 1,'Pois se opunham ao politeísmo dominante na época',0),
(160, 2,'Pois seus deuses, sempre prontos a castigar os pecadores, desencadearam o Dilúvio',0),
(160, 3,'Pois construíram túmulos em forma de pirâmides truncadas, erigidos para a eternidade',0),
(161, 0,'Iugoslávia',1),
(161, 1,'Tchecoslováquia',0),
(161, 2,'URSS',0),
(161, 3,'Império Otomano',0),
(162, 0,'Japão, Alemanha e Itália',1),
(162, 1,'Espanha, China e Alemanha',0),
(162, 2,'Japão, Espanha e Alemanha',0),
(162, 3,'Itália, Holanda e Alemanha',0),
(163, 0,'Pearl Harbor',1),
(163, 1,'Sewell''s Point',0),
(163, 2,'Norfolk',0),
(163, 3,'Newark',0),
(164, 0,'Itália',1),
(164, 1,'Alemanha',0),
(164, 2,'Espanha',0),
(164, 3,'Japão',0),
(165, 0,'França',1),
(165, 1,'Alemanha',0),
(165, 2,'Inglaterra',0),
(165, 3,'Holanda',0),
(166, 0,'Homo Sapiens Sapiens',1),
(166, 1,'Homem-de-neandertal',0),
(166, 2,'Australopithecus',0),
(166, 3,'Homo habilis',0),
(167, 0,'Uma revolução de ideias, após a Renascença, no final da Idade Média. São as ideias que trazem a luz após as trevas',1),
(167, 1,'Movimento artístico do século XX',0),
(167, 2,'Um evento no qual os bispos da igreja católica renunciaram seus cargos e deu início à outra era da história ocidental.',0),
(167, 3,'Uma revolução da ciência em geral.',0),
(168, 0,'Voltaire, Rousseau, Montesquieu, Hobbes e Locke',1),
(168, 1,'Nietzsche e Marx',0),
(168, 2,'Sócrates, Platão e Aristóteles',0),
(168, 3,'Foucault, Sartre e Beauvoir',0),
(169, 0,'Arquimedes',1),
(169, 1,'Aristóteles',0),
(169, 2,'Sócrates',0),
(169, 3,'Platão',0),
(170, 0,'Persa',1),
(170, 1,'Otomano',0),
(170, 2,'Bárbaro',0),
(170, 3,'Russo',0),
(171, 0,'Hieróglifo',1),
(171, 1,'Cuneiforme',0),
(171, 2,'Hebraico',0),
(171, 3,'Arcadiano',0),
(172, 0,'1453',1),
(172, 1,'1452',0),
(172, 2,'1456',0),
(172, 3,'1457',0),
(173, 0,'Nabucodonosor',1),
(173, 1,'Menés',0),
(173, 2,'Tutancâmon',0),
(173, 3,'Amenófis',0)

--Literatura
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Machado de Assis tinha a saúde abalada por qual doença?',																					6),
('Machado de Assis morreu com quantos anos?',																							 	6),
('Qual o nome do movimento literário que utilizava de Cantigas líricas e satíricas?',													 	6),
('''O Mulato'' e ''Memórias Póstumas de Brás Cubas'', de 1881, são obras que marcam o início do:',										 	6),
('Qual o herói do livro Os Lusíadas, de Camões?',																						 	6),
('Quem é o autor do livro ''Dom Quixote''?',																								6),
('Qual escritor brasileiro escreveu o romance intitulado ''Iracema''?',																	 	6),
('Quem escreveu a obra ''Ulysses''?',																									 	6),
('Qual dos escritores escreveu a ''Divina Comédia''?',																					 	6),
('Em que país nasceu Clarice Lispector?',																								 	6),
('Qual desses autores nunca atingiu a marca de 100 milhões de livros vendidos?',															6),
('''Ser ou não ser? eis a questão'' é uma das frases mais conhecidas e faladas do mundo, dita em qual obra de Shakespeare?',				6),
('''Drácula'' foi escrito por quem?',																									 	6),
('Qual o último livro publicado de Júlio Verne?',																						 	6),
('Qual destes personagens não pertence à autoria da romancista policial Agatha Christie?',												 	6),
('''Robinson Crusoe'' é um romance de Daniel Defoe que gira em torno de:',																 	6),
('A singular obra de Machado de Assis, Dom Casmurro, é narrada em primeira pessoa. Quem é o personagem-narrador da história?',			 	6),
('Qual destes foi um grande realista?'		,																								6)

--Literatura (terminando - faltam 12)
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
(174, 0, 'Epilepsia',1),
(174, 1, 'Pneumonia',0),
(174, 2, 'Cirrose',0),
(174, 3, 'Esquizofrenia',0),
(175, 0, '69 anos',1),
(175, 1, '72 anos',0),
(175, 2, '80 anos',0),
(175, 3, '76 anos',0),
(176, 0, 'Trovadorismo',1),
(176, 1, 'Humanismo',0),
(176, 2, 'Barroco',0),
(176, 3, 'Arcadismo',0),
(177, 0, 'Realismo no Brasil',1),
(177, 1, 'Romantismo no Brasil',0),
(177, 2, 'Naturalismo em Portugal',0),
(177, 3, 'Barroco no Brasil',0),
(178, 0, 'Vasco da Gama',1),
(178, 1, 'O próprio Camões',0),
(178, 2, 'Dom Pedro I',0),
(178, 3, 'O livro não trata de nenhum herói',0),
(179, 0, 'Miguel de Cervantes',1),
(179, 1, 'Luís de Camões',0),
(179, 2, 'Francisco de Quevedo',0),
(179, 3, 'Gil Vicente',0),
(180, 0, 'José de Alencar',1),
(180, 1, 'Machado de Assis',0),
(180, 2, 'Carlos Drummond de Andrade',0),
(180, 3, 'Graciliano Ramos',0),
(181, 0, 'James Joyce',1),
(181, 1, 'William Shakespeare',0),
(181, 2, 'Marcel Proust',0),
(181, 3, 'Richard Kipling',0),
(182, 0, 'Dante Alighieri',1),
(182, 1, 'Visconte de Taunay',0),
(182, 2, 'Gil Vicente',0),
(182, 3, 'Luís de Camões',0),
(183, 0, 'Ucrânia',1),
(183, 1, 'Brasil',0),
(183, 2, 'Portugal',0),
(183, 3, 'Suíça',0),
(184, 0, 'Rick Riordan (Percy Jackson)',1),
(184, 1, 'Stephenie Meyer',0),
(184, 2, 'Paulo Coelho',0),
(184, 3, 'Jeff Kinney',0),
(185, 0, 'Hamlet',1),
(185, 1, 'Romeu e Julieta',0),
(185, 2, 'Otelo',0),
(185, 3, 'A Megera Domada',0),
(186, 0, 'Bram Stocker',1),
(186, 1, 'Robert Louis Stevenson',0),
(186, 2, 'Júlio Verne',0),
(186, 3, 'William Shakespeare',0),
(187, 0, 'O Senhor do Mundo',1),
(187, 1, 'Viagem ao Centro da Terra',0),
(187, 2, 'A Volta ao Mundo em 80 Dias',0),
(187, 3, 'Cinco Semanas em um Balão',0),
(188, 0, 'Sherlock Holmes',1),
(188, 1, 'Tommy Beresford',0),
(188, 2, 'Hercule Poirot',0),
(188, 3, 'Prudence Cowley',0),
(189, 0, 'Um naufrágio',1),
(189, 1, 'Uma queda de avião',0),
(189, 2, 'Um assassinato',0),
(189, 3, 'Uma guerra',0),
(190, 0, 'Bento Santiago',1),
(190, 1, 'Escobar',0),
(190, 2, 'Capitu',0),
(190, 3, 'José Dias',0),
(191, 0, 'Eça de Queirós',1),
(191, 1, 'Euclides da Cunha',0),
(191, 2, 'Fernão Lopes',0),
(191, 3, 'Padre Antônio Vieira',0)
	
--Séries 
	
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Qual o nome do ator que faz a narração (Ted Mosby do futuro) de How I Met Your Mother?',												8),
('Qual o nome do(a) personagem adotado(a) na série The O.C.?',																			8),
('Qual o nome da atriz que interpreta as clones em Orphan Black?',																		8),
('Em Orphan Black, qual das clones comete suicídio?',																					8),
('Qual o nome da atriz que interpreta Alex Danvers na série Supergirl?',																8),
('Na série True Blood, o que representa True Blood?',																					8),
('Qual o nome da atriz que interpreta Sookie, em True Blood?',																			8),
('Em ''How I Met Your Mother'', qual o objeto que Ted roubou da parede do restaurante?',												8),
('Em ''Breaking Bad'', qual era o toque especial que Jesse Pinkman colocava nas drogas que produzia?',									8),
('Em ''Breaking Bad'', qual empreendimento Saul Goodman quer que Walter White compre para lavar dinheiro?',								8),
('Qual o nome dos três dragões de Daenerys Targaryen em Game of Thrones?',																8),
('Em ''Game of Thrones'', por que Hodor só consegue pronunciar seu nome?',																8),
('Em ''Game of Thrones'', os lemas ''crescendo fortes'' e ''família, dever, honra'' pertencem a quais casas respectivamente?',			8),
('Em ''White Collar'', qual o nome do ator que interpreta o agente Hilks?'	,														8)
    
--Séries
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
(192, 0, 'Bob Saget',1),
(192, 1, 'Josh Radnor',0),
(192, 2, 'Charlie Sheen',0),
(192, 3, 'Matthew Perry',0),
(193, 0, 'Ryan Atwood',1),
(193, 1, 'Seth Cohen',0),
(193, 2, 'Marissa Cooper',0),
(193, 3, 'Summer Roberts',0),
(194, 0, 'Tatiana Maslany',1),
(194, 1, 'Anna Torv',0),
(194, 2, 'Emily VanCamp',0),
(194, 3, 'Anna Gunn',0),
(195, 0, 'Beth',1),
(195, 1, 'Katja',0),
(195, 2, 'Jennifer',0),
(195, 3, 'MK',0),
(196, 0, 'Chyler Leigh',1),
(196, 1, 'Nina Dobrev',0),
(196, 2, 'Katie McGrath',0),
(196, 3, 'Calista Flockhart',0),
(197, 0, 'O sangue sintético que os cientistas criaram para que os vampiros possam viver entre humanos',1),
(197, 1, 'Sangue animal que os vampiros consomem para não precisar matar humanos',0),
(197, 2, 'O sangue de Sookie, pois ela é mais que humana',0),
(197, 3, 'O sangue de vampiros, pois faz com que humanos fiquem mais fortes',0),
(198, 0, 'Anna Paquin',1),
(198, 1, 'Deborah Ann Woll',0),
(198, 2, 'Adina Porter',0),
(198, 3, 'Kristin Bauer van Straten',0),
(199, 0, 'Trompa azul',1),
(199, 1, 'Flauta azul',0),
(199, 2, 'Saxofone azul',0),
(199, 3, 'Gaita azul',0),
(200, 0, 'Pimenta em pó',1),
(200, 1, 'Canela em pó',0),
(200, 2, 'Menta',0),
(200, 3, 'Corante azul',0),
(201, 0, 'Laser Tech',1),
(201, 1, 'Petshop',0),
(201, 2, 'Lava-rápido',0),
(201, 3, 'Lanchonete',0),
(202, 0, 'Drogon, Viserion e Rhaegal',1),
(202, 1, 'Rhaego, Viserys e Drogo',0),
(202, 2, 'Dracarys, Viserion e Drogon',0),
(202, 3, 'Drogon, Viserion e Rhaegal',0),
(203, 0, 'Ele ficou preso em uma visão do futuro que o atormentou, onde ele morria segurando a porta para que Bran fugisse',1),
(203, 1, 'Ele foi torturado durante anos pelos Bolton que o convenceram que seu nome era este',0),
(203, 2, 'Ele foi submetido a uma tortura mental onde ele precisou ouvir pessoas pronunciarem aquele nome por várias horas, durante dias',0),
(203, 3, 'Ele era doente mental e sua mãe só conseguiu ensiná-lo seu nome',0),
(204, 0, 'Tyrell e Tully',1),
(204, 1, 'Stark e Lannister',0),
(204, 2, 'Tyrell e Stark',0),
(204, 3, 'Lannister e Tully',0),
(205, 0, 'Sharif Atkins',1),
(205, 1, 'Willie Garson',0),
(205, 2, 'Tim DeKay',0),
(205, 3, 'Jeff Eastin',0)

-- Lógica
INSERT INTO Pergunta (descricao, codCategoria) VALUES
('Se anteontem foi sábado, que dia é depois de amanhã?',9),
('Maria tinha alguns biscoitos. Ela comeu dois e deu dois à irmã. Depois deu metade do que sobrou ao irmão. Se o irmão ficou com 5 biscoitos, quantos tinha Maria no início?',9),
('Um dos elementos relacionados abaixo não está de acordo com os demais do grupo.',9),
('Dentre os itens abaixo, qual aquele que pode ser considerado um intruso?',9),
('''Amigo'' está para ''Inimigo'' assim como ''Alegria'' está para:',9),
('''Cabeça'' está para ''Pé'' assim como ''Teto'' está para:',9),
('Coloque as Frutas na ordem Correta: Jaca(1) - Cereja(2) - Limão(3) - Melão(4)',9),
('Brilhante está para Obscuro assim como Hesitação está para:',9),
('O Termômetro subiu 6 graus, o que representa a metade da temperatura de antes. A quantos graus está agora?',9),
('O Avicultor diz: ''Se eu tivesse dois Patos a mais, o dobro desse número seria 100.'' Quantos Patos tem ele?',9),
('Zezinho tem 24 bolas. Dá 4 para Luizinho e ambos ficarão com quantidade igual. Quantas bolas tinhas Luizinho inicialmente?',9),
('Pedrinho tem 6 bolas a mais do que Chico. Os dois juntos têm 54. Quanto tem cada um?',9),
('Seis pessoas comem 6 biscoitos em seis minutos. Quantas pessoas comerão 80 biscoitos em 48 minutos?',9),
('Perguntado pela idade, Pedro responde: ''Daqui a 30 anos, terei três vezes a idade de agora.'' Qual a idade de Pedro?',9),
('A Mãe é três vezes mais velha que a filha. Juntas têm 48 anos. Qual é a idade de cada uma?',9),
('Se estivessem na sala de aula 5 alunos mais, a metade deles seria 20 alunos. Quantos estão lá realmente?',9),
('Oito estudantes se encontram e cada um cumprimenta o outro com um aperto de mão. Quantos apertos de mão se trocaram?',9)

-- Lógica
INSERT INTO Alternativa (codPergunta, codAlternativa, alternativa, situacao) VALUES
(206, 0, 'Quarta-feira',1),
(206, 1, 'Sexta-feira',	0),
(206, 2, 'Domingo',		0),
(206, 3, 'Terça-feira',	0),
(207,0,'14 Biscoitos',1),
(207,1,'12 Biscoitos',0),
(207,2,'20 Biscoitos',0),
(207,3,'13 Biscoitos',0),
(208,0,'Maracujá',1),
(208,1,'Ameixa',0),
(208,2,'Abacate',0),
(208,3,'Manga',0),
(209,0,'Vaca',1),
(209,1,'Hiena',0),
(209,2,'Gato',0),
(209,3,'Leão',0),
(210,0,'Tristeza',1),
(210,1,'Sonho',0),
(210,2,'Risos',0),
(210,3,'Felicidade',0),
(211,0,'Chão',1),
(211,1,'Telhado',0),
(211,2,'Parede',0),
(211,3,'Porta',0),
(212,0,'1 - 4 - 3 - 2',1),
(212,1,'2 - 1 - 3 - 4',0),
(212,2,'3 - 2 - 1 - 4',0),
(212,3,'2 - 3 - 4 - 1',0),
(213,0,'Firmeza',1),
(213,1,'Dúvida',0),
(213,2,'Indecisão',0),
(213,3,'Êxito',0),
(214,0,'18 graus',1),
(214,1,'12 graus',0),
(214,2,'16 graus',0),
(214,3,'9 graus',0),
(215,0,'48 Patos',1),
(215,1,'80 Patos',0),
(215,2,'54 Patos',0),
(215,3,'60 Patos',0),
(216,0,'16',1),
(216,1,'14',0),
(216,2,'12',0),
(216,3,'18',0),
(217,0,'Pedrinho tem 30, Chico 24',1),
(217,1,'Pedrinho tem 28, Chico 22',0),
(217,2,'Pedrinho tem 24, Chico 30',0),
(217,3,'Pedrinho tem 36, Chico 30',0),
(218,0,'10 pessoas',1),
(218,1,'14 pessoas',0),
(218,2,'15 pessoas',0),
(218,3,'12 pessoas',0),
(219,0,'15 anos',1),
(219,1,'13 anos',0),
(219,2,'14 anos',0),
(219,3,'18 anos',0),
(220,0,'36 e 12',1),
(220,1,'34 e 14',0),
(220,2,'32 e 16',0),
(220,3,'30 e 18',0),
(221,0,'35',1),
(221,1,'32',0),
(221,2,'38',0),
(221,3,'34',0),
(222,0,'28',1),
(222,1,'32',0),
(222,2,'26',0),
(222,3,'34',0)

INSERT INTO PerguntasRespondidas (codUsuario, codQuiz, codPergunta, respostaUsuario, pontuacaoPergunta) VALUES
(1, '1',  1, 0, 50),
(1, '1',  5, 1, 50),
(1, '1',  8, 2, 50),
(1, '1',  9, 1, 50),
(1, '1', 13, 0, 50),
(1, '1', 18, 3, 50),
(1, '1', 19, 3, 50),
(1, '1', 22, 2, 50),
(1, '1', 26, 2, 50),
(1, '1', 29, 0, 50),
(2, '2', 32, 0, 44),
(2, '2', 36, 0, 0),
(2, '2', 39, 2, 35),
(2, '2', 43, 3, 0),
(2, '2', 44, 3, 38),
(2, '2', 48, 1, 40),
(2, '2', 54, 1, 27),
(2, '2', 57, 0, 0),
(2, '2', 58, 1, 50),
(2, '2', 60, 2, 0)
